# .github/workflows/deploy.yml
name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Create app directory if it doesn't exist
          sudo mkdir -p /opt/workout-tracker
          sudo chown ${{ secrets.SERVER_USERNAME }}:${{ secrets.SERVER_USERNAME }} /opt/workout-tracker
          
          # Pull latest code
          cd /opt/workout-tracker
          git pull origin main || git clone ${{ secrets.REPO_URL }} .
          
          # Install/update dependencies
          python3 -m pip install -r requirements.txt
          
          # Restart service
          sudo systemctl restart workout-tracker